#!/usr/bin/env python3
"""
Recalculate Drivability Maps
============================
Reads older semantic label maps from `OLDsemantics/` generated by previous iterations
of the Grounding DINO logic, and generates fresh `drivability/` maps while explicitly
setting all UNLABELLED pixels (index 255) to a safe drivability score of 1.0.

Usage:
    python recalculate_drivability.py --data_root /data_224 --viz
"""

import os
import glob
import argparse
import numpy as np
import cv2
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed

# Original categories to match the OLDsemantics arrays
CATEGORIES = [
    "road",         # 0
    "sidewalk",     # 1
    "car",          # 2
    "bus",          # 3
    "vehicle",      # 4
    "cyclist",      # 5
    "pedestrian",   # 6
    "building",     # 7
    "tree",         # 8
    "bush",         # 9
    "sky",          # 10
]

DRIVABILITY = {
    "road":         1.0,
    "sidewalk":     0.0,
    "car":          0.0,
    "bus":          0.0,
    "vehicle":      0.0,
    "cyclist":      0.0,
    "pedestrian":   0.0,
    "building":     0.0,
    "tree":         0.0,
    "bush":         0.0,
    "sky":          0.5,
}

UNLABELLED_IDX = 255
UNLABELLED_DRIVABILITY = 1.0  # As requested, don't penalize unlabelled pixels!

def save_drivability_visualisation(img_path, drivability_map, out_path):
    img = cv2.imread(str(img_path))
    if len(img.shape) == 3 and img.shape[2] == 3:
        img = cv2.cvtColor(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), cv2.COLOR_GRAY2BGR)
    elif len(img.shape) == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    
    score_scaled = ((1.0 - drivability_map) * 255.0).clip(0, 255).astype(np.uint8)
    heatmap = cv2.applyColorMap(score_scaled, cv2.COLORMAP_JET)
    blended = cv2.addWeighted(img, 0.6, heatmap, 0.4, 0)
    cv2.imwrite(str(out_path), blended)

def process_sequence(seq_path, args):
    old_sem_dir = os.path.join(seq_path, "OLDsemantics")
    drv_dir = os.path.join(seq_path, "drivability")
    image_dir = os.path.join(seq_path, "images")
    
    if not os.path.isdir(old_sem_dir):
        return 0, f"Skipping {os.path.basename(seq_path)} (no OLDsemantics/ folder)"
        
    os.makedirs(drv_dir, exist_ok=True)
    if args.viz:
        drv_vis_dir = os.path.join(seq_path, "drivability_vis")
        os.makedirs(drv_vis_dir, exist_ok=True)
        
    files = glob.glob(os.path.join(old_sem_dir, "*.npy"))
    if not files:
        return 0, f"{os.path.basename(seq_path)} OLDsemantics/ is empty."

    num_processed = 0
    cat_to_score = {i: DRIVABILITY[cat] for i, cat in enumerate(CATEGORIES)}
    
    for f in tqdm(files, desc=os.path.basename(seq_path), leave=False):
        fname = os.path.basename(f)
        fname_noext = os.path.splitext(fname)[0]
        
        # Load the old semantic map
        label_map = np.load(f)
        h, w = label_map.shape
        
        # Re-assign drivability scores instantly via vectorization
        drv_map = np.full((h, w), UNLABELLED_DRIVABILITY, dtype=np.float32)
        for idx in cat_to_score:
            drv_map[label_map == idx] = cat_to_score[idx]
            
        # Apply Gaussian smoothing blur around obstacles
        ksize = int(w / 16)
        if ksize % 2 == 0: ksize += 1
        drv_map = cv2.GaussianBlur(drv_map, (ksize, ksize), 0)
        drv_map = drv_map.astype(np.float16)
        
        # Save drivability map as .npy (keeping consistency with the rest of the stack)
        np.save(os.path.join(drv_dir, fname), drv_map)
        
        # Optional Visualisation
        if args.viz:
            img_path = os.path.join(image_dir, f"{fname_noext}.png")
            if not os.path.exists(img_path):
                img_path = os.path.join(image_dir, f"{fname_noext}.jpg")
                
            if os.path.exists(img_path):
                out_path = os.path.join(drv_vis_dir, f"{fname_noext}_drv.png")
                save_drivability_visualisation(img_path, drv_map, out_path)
                
        num_processed += 1
        
    return num_processed, f"{os.path.basename(seq_path)}: Re-processed {num_processed} maps."

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_root", type=str, required=True, help="Path to /data_224 or dataset root")
    parser.add_argument("--viz", action="store_true", help="Generate the colour-coded overlays in drivability_vis/")
    parser.add_argument("--workers", type=int, default=os.cpu_count(), help="Number of CPU cores to use")
    args = parser.parse_args()

    seq_folders = sorted([
        os.path.join(args.data_root, d)
        for d in os.listdir(args.data_root)
        if os.path.isdir(os.path.join(args.data_root, d))
    ])

    print(f"\nRecalculating Drivability Maps")
    print(f"Data root: {args.data_root}")
    print(f"Workers: {args.workers}")
    print(f"Unlabelled Default: {UNLABELLED_DRIVABILITY}\n")

    total = 0
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(process_sequence, seq, args): seq for seq in seq_folders}
        for future in as_completed(futures):
            num, msg = future.result()
            total += num
            print(msg)
            
    print(f"\nDone! Successfully recalculated {total} drivability maps.")

if __name__ == "__main__":
    main()
